title: Pitchicle
email: cbshpitchicle@gmail.com
description: "평등으로의 한 걸음, 모두를 위한 과학"

baseurl: ''
url: 'https://pitchicle.github.io'
timezone: Asia/Seoul 

repository: pitchicle/pitchicle.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge
 
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/
  feedback:
    output: true
    permalink: /feedback/:path/
  drafts:
    output: true
    permalink: /drafts/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: cbshpitchicle@gmail.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-203797473-1'
twitter:
  username: Pitch_article
